# Generated by Django 4.2.1 on 2023-05-21 20:29

import app1.manager
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('description', models.CharField(default='', max_length=200)),
                ('image', models.ImageField(upload_to='products')),
            ],
        ),
        migrations.AlterModelManagers(
            name='customer',
            managers=[
                ('objects', app1.manager.UserManager()),
            ],
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='mobile',
            new_name='number',
        ),
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(blank=True, unique=True),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('description', models.CharField(default='', max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='products')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.category')),
            ],
        ),
    ]
