# Generated by Django 4.2.1 on 2023-06-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_customer_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
    ]
