# Generated by Django 4.2.1 on 2023-06-08 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_customer_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_offer',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='category_offer_description',
            field=models.CharField(default='', max_length=100),
        ),
    ]
