# Generated by Django 4.2.1 on 2023-06-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_customer_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='referral_amount',
            field=models.IntegerField(default=0),
        ),
    ]
