# Generated by Django 4.2.1 on 2023-05-23 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopper', '0004_address_wishlist_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
