# Generated by Django 4.2.1 on 2023-05-24 01:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopper', '0006_alter_order_payment_type_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
