# Generated by Django 4.2.1 on 2023-05-24 01:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopper', '0007_address_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='date',
        ),
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
