# Generated by Django 4.2.1 on 2023-05-31 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopper', '0008_remove_address_date_order_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=10)),
                ('expired', models.BooleanField(default=False)),
                ('discout_price', models.PositiveIntegerField(default=100)),
                ('minimum_amount', models.PositiveIntegerField(default=500)),
                ('expiry_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
