# Generated by Django 4.2.1 on 2023-05-31 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopper', '0009_coupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='discout_price',
            new_name='discount_price',
        ),
    ]
