# Generated by Django 4.2.1 on 2023-06-01 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopper', '0010_rename_discout_price_coupon_discount_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='coupon_code',
            field=models.CharField(max_length=100),
        ),
    ]
