# Generated by Django 4.2.1 on 2023-06-13 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopper', '0013_alter_order_product_alter_order_quantity_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
    ]
